import { createSlice } from "@reduxjs/toolkit";
const products = [
  // AGARWOOD (OUD)
  {
    id: "oud-bracelet-001",
    category: "agarwood",
    type: "bracelet",
    name: "Royal Assam Oud Bracelet",
    subtitle: "Premium Grade A Agarwood",
    description:
      "Hand-crafted from rare Assam Agarwood, each bead holds centuries of ancient resin. The deep,smoky fragrance evolves on the skin throughout the day. A spiritual adornment revered across Arabia and Asia.",
    longDescription:
      "Sourced from the Aquilaria malaccensis tree in the pristine forests of Assam, India — the world's first nation to harvest agarwood sustainably. Each bracelet is hand-strung by master artisans using 10mm beads aged over 15 years. The resin content (oleoresin) exceeds 25%, making these Grade A pieces cherished by collectors and royalty alike.",
    origin: "Assam, India",
    grade: "Grade A",
    beadSize: "10mm",
    beads: 21,
    purpose: ["Hindu Japa", "Muslim Dhikr", "Luxury Wear"],
    scent: "Deep woody, smoky, balsamic",
    sustainabilityNote: "Ethically harvested with CITES compliance",
    images: [
      "https://images.unsplash.com/photo-1601924582970-9238bcb495d9?w=800",
      "https://images.unsplash.com/photo-1609619385002-f40f1df3e3f6?w=800",
    ],
    prices: {
      INR: 4500,
      USD: 54,
      AED: 198,
      SAR: 202,
      JPY: 8100,
      CNY: 390,
      QAR: 197,
    },
    rating: 4.9,
    reviews: 128,
    stock: 24,
    badge: "Bestseller",
    relatedIds: ["oud-mala-001", "oud-oil-001"],
  },
  {
    id: "oud-mala-hindu-001",
    category: "agarwood",
    type: "mala",
    name: "Agarwood Japa Mala — 108 Beads",
    subtitle: "Sacred Hindu Prayer Mala",
    description:
      "A sacred 108-bead Japa mala handcrafted from premium agarwood. Each repetition of your mantra is accompanied by the divine fragrance of oud — deepening meditation and spiritual focus.",
    longDescription:
      "Used for thousands of years in Vedic traditions, this mala carries 108 sacred beads — representing the 108 Upanishads and the distance between the Sun and Earth. The natural agarwood scent intensifies with warmth, making each meditation session an olfactory journey. Includes a Guru bead and tassel.",
    origin: "Assam, India",
    grade: "Grade B+",
    beadSize: "8mm",
    beads: 108,
    purpose: ["Hindu Japa Mala", "Vedic Meditation"],
    scent: "Earthy, warm, spiritual",
    sustainabilityNote: "CITES certified",
    images: [
      "https://images.unsplash.com/photo-1609198093478-2e6bca3e3c75?w=800",
    ],
    prices: {
      INR: 6800,
      USD: 82,
      AED: 301,
      SAR: 307,
      JPY: 12300,
      CNY: 592,
      QAR: 299,
    },
    rating: 4.8,
    reviews: 96,
    stock: 18,
    badge: "Spiritual",
    relatedIds: ["oud-bracelet-001", "oud-oil-001"],
  },
  {
    id: "oud-mala-muslim-001",
    category: "agarwood",
    type: "mala",
    name: "Agarwood Tasbih — 99 Beads",
    subtitle: "Premium Islamic Prayer Beads",
    description:
      "A luxurious 99-bead Tasbih for dhikr, crafted from wild-harvested agarwood. The subtle oud fragrance elevates every SubhanAllah, Alhamdulillah and Allahu Akbar.",
    longDescription:
      "Agarwood (Oud) holds a special place in Islamic tradition. The Prophet Muhammad  reportedly used oud in spiritual practices. Each bead of this tasbih is hand-polished and carries natural resin scent. Divided into three sections of 33 beads with silver-toned dividers. Presented in a hand-stitched velvet pouch.",
    origin: "Assam, India",
    grade: "Grade A",
    beadSize: "10mm",
    beads: 99,
    purpose: ["Islamic Dhikr", "Tasbih", "Gifting"],
    scent: "Rich, warm, sacred",
    sustainabilityNote: "Ethically sourced",
    images: [
      "https://images.unsplash.com/photo-1591981563701-81c0e7f4ad4f?w=800",
    ],
    prices: {
      INR: 7200,
      USD: 87,
      AED: 319,
      SAR: 326,
      JPY: 13000,
      CNY: 628,
      QAR: 317,
    },
    rating: 4.9,
    reviews: 214,
    stock: 15,
    badge: "Top Rated",
    relatedIds: ["oud-bracelet-001", "oud-chips-001"],
  },
  {
    id: "oud-oil-001",
    category: "agarwood",
    type: "oil",
    name: "Pure Agarwood Oil — Dehn Al Oud",
    subtitle: "First Distillation · Non-Alcoholic",
    description:
      "The world's most precious perfume oil. First-distillation dehn al oud from Grade A Assam agarwood chips. A single dab on the wrist releases hours of complex, evolving fragrance.",
    longDescription:
      "Distilled using traditional hydro-distillation over 48 hours, this non-alcoholic attar captures the full spectrum of agarwood's aromatic compounds. The scent opens with barnyard animalic notes, transitions through sweet woods and incense, settling into a long-lasting dry-down of leather and earth. Favoured in UAE, Saudi Arabia and Japan. 3ml, 6ml, and 12ml available.",
    origin: "Assam, India",
    grade: "First Distillation",
    variants: ["3ml", "6ml", "12ml"],
    purpose: ["Personal Fragrance", "Arabic Perfumery", "Meditation"],
    scent: "Animalic, woody, incense, leather",
    sustainabilityNote: "CITES compliant export",
    images: [
      "https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?w=800",
    ],
    prices: {
      INR: 3200,
      USD: 38,
      AED: 140,
      SAR: 143,
      JPY: 5800,
      CNY: 278,
      QAR: 138,
    },
    rating: 5.0,
    reviews: 302,
    stock: 40,
    badge: "Rare",
    relatedIds: ["oud-chips-001", "oud-bracelet-001"],
  },
  {
    id: "oud-chips-001",
    category: "agarwood",
    type: "chips",
    name: "Agarwood Chips — Bakhoor Grade",
    subtitle: "For Incense Burning · Burner Ready",
    description:
      "Premium agarwood chips for bakhoor (incense burning). Place on a traditional mabkhara or electric burner to fill any space with the legendary fragrance of oud — a tradition of hospitality across Arabia.",

    longDescription:
      "These bakhoor-grade chips contain high natural resin content, producing thick, lingering smoke with rich oud fragrance. Popular across UAE, Saudi Arabia, Qatar, and increasingly in Japan and China. Each batch is selected for minimum 20% resin content. Available in 10g, 25g, and 50g pouches. Can also be used in homes, mosques, and at special occasions.",
    origin: "Assam, India",
    grade: "Bakhoor Grade",
    variants: ["10g", "25g", "50g"],
    purpose: ["Bakhoor Burning", "Home Fragrance", "Ritual Use"],
    scent: "Intense, smoky, sweet-woody",
    sustainabilityNote: "CITES certified",
    images: [
      "https://images.unsplash.com/photo-1609619385002-f40f1df3e3f6?w=800",
    ],
    prices: {
      INR: 1800,
      USD: 22,
      AED: 80,
      SAR: 82,
      JPY: 3200,
      CNY: 154,
      QAR: 80,
    },
    rating: 4.7,
    reviews: 178,
    stock: 60,
    badge: "Value",
    relatedIds: ["oud-oil-001", "oud-mala-muslim-001"],
  },
  // SANDALWOOD
  {
    id: "sand-bracelet-001",
    category: "sandalwood",
    type: "bracelet",
    name: "Mysore Sandalwood Bracelet",
    subtitle: "Authentic Karnataka Sandalwood",
    description:
      "Carved from the finest Mysore sandalwood — the most fragrant variety in the world. Wearing this bracelet means carrying the sacred essence of India's most protected wood.",
    longDescription:
      "Mysore sandalwood (Santalum album) from Karnataka is protected by the Indian government due to its exceptional oil content and fragrance. Our bracelets are carved by certified artisans from legally sourced wood. The creamy, milky-sweet scent is immediately recognisable and deeply calming. Each bracelet is unique — no two pieces are identical.",
    origin: "Mysore, Karnataka, India",
    grade: "Premium",
    beadSize: "8mm",
    beads: 21,
    purpose: ["Hindu Prayer", "Spiritual Wear", "Gifting"],
    scent: "Creamy, milky-sweet, warm woody",
    sustainabilityNote: "Legally sourced Karnataka sandalwood",
    images: [
      "https://images.unsplash.com/photo-1601924582970-9238bcb495d9?w=800",
    ],
    prices: {
      INR: 2200,
      USD: 26,
      AED: 96,
      SAR: 98,
      JPY: 3900,
      CNY: 188,
      QAR: 95,
    },
    rating: 4.8,
    reviews: 156,
    stock: 35,
    badge: "Heritage",
    relatedIds: ["sand-mala-001", "sand-oil-001"],
  },
  {
    id: "sand-mala-hindu-001",
    category: "sandalwood",
    type: "mala",
    name: "Sandalwood Japa Mala — 108 Beads",
    subtitle: "Vedic Tradition · Handstrung",
    description:
      "A traditional 108-bead sandalwood mala for Hindu worship, yoga, and meditation. The natural fragrance of sandalwood purifies the mind and invites deeper states of consciousness.",
    longDescription:
      "Sandalwood has been integral to Hindu ritual since the Vedic era. Used in puja, applied as chandan tilak on the forehead, and strung into sacred malas. This 108-bead mala uses 8mm Mysore sandalwood beads, hand-strung on red silk thread — the traditional color of devotion. Ideal for Vishnu and Devi mantras.",
    origin: "Mysore, Karnataka, India",
    grade: "Premium",
    beadSize: "8mm",
    beads: 108,
    purpose: ["Hindu Japa", "Meditation", "Puja"],
    scent: "Soft, creamy, sacred",
    sustainabilityNote: "Legally sourced",
    images: [
      "https://images.unsplash.com/photo-1609198093478-2e6bca3e3c75?w=800",
    ],
    prices: {
      INR: 3800,
      USD: 46,
      AED: 169,
      SAR: 172,
      JPY: 6900,
      CNY: 331,
      QAR: 168,
    },
    rating: 4.9,
    reviews: 203,
    stock: 22,
    badge: "Sacred",
    relatedIds: ["sand-bracelet-001", "sand-oil-001"],
  },
  {
    id: "sand-mala-muslim-001",
    category: "sandalwood",
    type: "mala",
    name: "Sandalwood Tasbih — 99 Beads",
    subtitle: "Islamic Prayer Beads · Fragrant",
    description:
      "A 99-bead sandalwood tasbih with the gentle, enduring scent of Mysore sandalwood. A beautiful companion for daily dhikr and a cherished gift.",
    longDescription:
      "Sandalwood's calming fragrance has been used in Islamic spiritual practices across South Asia and Southeast Asia for centuries. This tasbih features 99 smooth-polished sandalwood beads divided into three sections of 33, with silver spacers. The natural wood oil intensifies with use over months, making each tasbih increasingly precious.",
    origin: "Mysore, Karnataka, India",
    grade: "Premium",
    beadSize: "10mm",
    beads: 99,
    purpose: ["Islamic Dhikr", "Tasbih", "Daily Prayer"],
    scent: "Gentle, warm, enduring",
    sustainabilityNote: "Karnataka certified",
    images: [
      "https://images.unsplash.com/photo-1591981563701-81c0e7f4ad4f?w=800",
    ],
    prices: {
      INR: 4200,
      USD: 50,
      AED: 184,
      SAR: 188,
      JPY: 7600,
      CNY: 366,
      QAR: 183,
    },
    rating: 4.7,
    reviews: 87,
    stock: 30,
    badge: "Gifting",
    relatedIds: ["sand-bracelet-001", "sand-powder-001"],
  },
  {
    id: "sand-oil-001",
    category: "sandalwood",
    type: "oil",
    name: "Pure Mysore Sandalwood Oil",
    subtitle: "100% Pure · Steam Distilled",
    description:
      "Steam-distilled from mature Mysore sandalwood heartwood. One of the rarest natural perfume ingredients in the world — a single 5ml vial represents over 30 years of tree growth.",
    longDescription:
      "Authentic Mysore sandalwood oil (Santalum album) is steam-distilled from heartwood aged 30+ years. The Karnataka Forest Department regulates all production. Our oil has minimum 90% alpha-beta santalol content — the therapeutic and aromatic benchmark. Used in Ayurveda, Hindu ritual, high-end perfumery, and skincare. Available in 2.5ml, 5ml, and 10ml.",
    origin: "Mysore, Karnataka, India",
    grade: "Pure Steam Distilled",
    variants: ["2.5ml", "5ml", "10ml"],
    purpose: ["Perfumery", "Ayurveda", "Meditation", "Skincare"],
    scent: "Milky, creamy, sweet, musky dry-down",
    sustainabilityNote: "Karnataka govt. licensed",
    images: [
      "https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?w=800",
    ],
    prices: {
      INR: 2800,
      USD: 34,
      AED: 124,
      SAR: 127,
      JPY: 5100,
      CNY: 244,
      QAR: 123,
    },
    rating: 5.0,
    reviews: 267,
    stock: 45,
    badge: "Pure",

    relatedIds: ["sand-powder-001", "sand-bracelet-001"],
  },
  {
    id: "sand-powder-001",
    category: "sandalwood",
    type: "powder",
    name: "Mysore Sandalwood Powder",
    subtitle: "Ritual & Cosmetic Grade",
    description:
      "Fine-ground Mysore sandalwood powder for puja, tilak application, face packs, and ritual use. The golden-hued powder carries the same divine fragrance as the heartwood.",
    longDescription:
      "Ground from mature Mysore sandalwood heartwood, this powder is a staple of Hindu ritual and Ayurvedic skincare. Used to make chandan paste for deity worship, applied as a cooling tilak on the forehead, and mixed with rose water for skin brightening. 100% pure, no fillers or synthetic fragrance. Available in 50g, 100g, and 250g pouches. Popular in Japan for traditional cosmetic use.",
    origin: "Mysore, Karnataka, India",
    grade: "Cosmetic / Ritual Grade",
    variants: ["50g", "100g", "250g"],
    purpose: ["Hindu Ritual", "Ayurvedic Skincare", "Tilak", "Face Pack"],
    scent: "Soft, creamy, faintly sweet",
    sustainabilityNote: "Government regulated",
    images: [
      "https://images.unsplash.com/photo-1609619385002-f40f1df3e3f6?w=800",
    ],
    prices: {
      INR: 980,
      USD: 12,
      AED: 44,
      SAR: 45,
      JPY: 1800,
      CNY: 86,
      QAR: 43,
    },
    rating: 4.6,
    reviews: 189,
    stock: 80,
    badge: "Daily Use",
    relatedIds: ["sand-oil-001", "sand-mala-hindu-001"],
  },
];

const productsSlice = createSlice({
  name: "products",
  initialState: {
    items: products,
    featured: [
      "oud-oil-001",
      "sand-oil-001",
      "oud-mala-muslim-001",
      "sand-bracelet-001",
    ],
    loading: false,
  },
  reducers: {},
});

export const selectAllProducts = (state) => state.products.items;
export const selectFeaturedIds = (state) => state.products.featured;
export const selectProductById = (id) => (state) =>
  state.products.items.find((p) => p.id === id);
export const selectByCategory = (cat) => (state) =>
  state.products.items.filter((p) => p.category === cat);
export const selectByType = (type) => (state) =>
  state.products.items.filter((p) => p.type === type);

export default productsSlice.reducer;
